#Hi, I'm a new developer, the MiniCore will be updated as I learn.
#If you have any questions or problems, join the discord : https://discord.gg/ZjwruYffD4

messages:
  discord: "&8[&a&l!!!&8] &6Our discord : &e&lhttps://discord.gg/ZjwruYffD4" # Permission : Default
  heal: "&8[&a&l!!!&8] &a&lYou get healed !" # Permission : heal.minicore
  feed: "&8[&a&l!!!&8] &a&lYou get Feed !"  # Permission : feed.minicore
  feedheal: "&8[&a&l!!!&8] &a&lYou get Feed and Heal !"  # Permission : feedheal.minicore
  id: "&8[&a&l!!!&8] &6ID : &e&l%id%" # Permission : id.minicore
  lobbyset: "&8[&a&l!!!&8] &a&lSuccefully configured the lobby location, is this correct?" # Permission : setlobby.minicore
  lobbyteleported: "&8[&a&l!!!&8] &a&lSuccefully teleported to the lobby !" # Permission : Default

gamemode:
  gmc: "&8[&a&l!!!&8] &a&lYou are now in &e&lCreative &a&l!" # Permission : gmc.minicore
  gms: "&8[&a&l!!!&8] &a&lYou are now in &e&lSurvival &a&l!" # Permission : gms.minicore
  gmsp: "&8[&a&l!!!&8] &a&lYou are now in &e&lSpectator &a&l!" # Permission : gmsp.minicore

fly: # Permssion Fly : fly.minicore || Permssion Speed : fly.speed
  noperm: "&8[&c&l!!!&8] &a&lYou dont have permission"
  enable: "&8[&a&l!!!&8] &a&lFly enable &a&l!"
  disable: "&8[&a&l!!!&8] &a&lFly &cdisable &a&l!"
  flyspeed: "&8[&a&l!!!&8] &a&lYour fly go at &e%speed% &a!"
  speed: "&8[&c&l!!!&8] &c&lThe max you can go its 5 and the less 1 !"
  onlynumber: "&8[&c&l!!!&8] &c&lYou can only use Numbers !"

#TOUCH THAT IF YOU ARE A ASSHOLE !!!
lobby:







