name: MiniCore
version: 1.2
api-version: 1.8
main: me.frenchguys.minicore.Main
description: MiniCore
author: FrenchGuys
discord: https://discord.gg/ZjwruYffD4

commands:
  discord:
    description: Give your Discord
    default: true
  heal:
    description: Heal yourself
    permission: heal.minicore
  feed:
    description: Feed yourself
    permission: feed.minicore
  feedheal:
    description: Feed and Heal yourself
    permission: feedheal.minicore
  gmc:
    description: Make yourself in Creative
    permission: gmc.minicore
  gms:
    description: Make yourself in Survival
    permission: gms.minicore
  gmsp:
    description: Make yourself in Spectator
    permission: gmsp.minicore
  id:
    description: Give the id of the block or the Items in your hands
    permission: id.minicore
  fly:
    description: Make yourself Fly
    permission: fly.minicore
  flyspeed:
    description: Change the speed of your Fly
    permission: fly.speed
  setlobby:
    permission: setlobby.minicore
    description: Set the Lobby of your server !
  lobby:
    description: Go to the Lobby !
    default: true