name: MiniCore
version: 1.2
api-version: 1.8
main: me.frenchguys.minicore.Main
description: MiniCore
author: FrenchGuys
discord: https://discord.gg/ZjwruYffD4

commands:
  discord:
    description: Give your Discord
    default: true
  heal:
    description: Heal yourself
  feed:
    description: Feed yourself
  feedheal:
    description: Feed and Heal yourself
  gmc:
    description: Make yourself in Creative
  gms:
    description: Make yourself in Survival
  gmsp:
    description: Make yourself in Spectator
  id:
    description: Give the id of the block or the Items in your hands
    default: true
  fly:
    description: Make yourself Fly
  flyspeed:
    description: Change the speed of your Fly
  setlobby:
    description: Set the Lobby of your server !
  lobby:
    description: Go to the Lobby !
    default: true

permissions:
  permissions.feed:
    description: Feed your self
    default: op
  permissions.heal:
    description: Heal your self
    default: op
  permissions.feedheal:
    description: Feed & Feed your self
    default: op
  permissions.fly:
    description: Fly
    default: op
  permissions.gmc:
    description: Gamemode C
    default: op
  permissions.gms:
    description: Gamemode S
    default: op
  permissions.gmsp:
    description: Gamemode Specatro
    default: op
  permissions.flyspeed:
    description: Fly speed
    default: op
  permissions.setlobby:
    description: Set the lobby
    default: op

